### ISSUE TITLE
Feature Request: Add firmware update functionality in web interface

### ISSUE THREAD

**Issue by andreas-bulling** [Tinkerforge/warp-charger#39] opened 2023-11-25 05:12 UTC
I'd be nice if the Warp Charger and EM offered functionality to update the firmware through the web interface, similar to other projects, such as Valetudo or Nextcloud. That is, the possibility to check whether a new firmware is available and the possibility to then update the firmware to that version if desired. Maybe also a checkbox that allows to select the update channel (stable or beta).

**Comment by photron** [comment] 2023-11-27 09:14
Duplicate of https://github.com/Tinkerforge/esp32-firmware/issues/88.

**Closed by photron** 2023-11-27 09:14 UTC
